name: Publish Tag
on:
  push

jobs:
  build:
    name: Publish Tag and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: set_var
        run: |
          content=`cat ./package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"

      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"

      - name: Bump version and push tag
        uses: ChloePlanet/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: "${{fromJson(steps.set_var.outputs.packageJson).version}}"